### ISSUE TITLE
Task: Extraire et transférer le contenu exporté du Wordpress

### ISSUE THREAD

**Issue by iolyd** [CUPUM/cupum.github.io#16]
### Task description

(Suite logique de #4)

Nous avons dorénavant un export complet de l'ancien site de la chaire, incluant sa base de données SQL. Nous devrions être en mesure de confectionner des commandes SQL pour exporter les données qui nous intéressent avec le format de notre choix.

### List of actions

- [ ] Faire un setup minimal pour rouler des commandes manuellement
- [ ] Tenter de manipuler l'export SQL
- [ ] Exporter les nouvelles
- [ ] Exporter ...?
