### ISSUE TITLE
Epic: Launch intermediary site'

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#19]
# Epic description 
We launch an intermediary website that take advanatage of the capacities of GitHub Pages, Jekyll following the recommendations of ChatGPT

# List of tasks:
- [ ] Task: Code Home page
- [ ] Task: Code About page
- [ ] Task: Code Projects page
- [ ] Task: Code Teaching page
