### ISSUE TITLE
Task: Résoudre erreur de sécurité en lien avec adresse de l'ancien site

### ISSUE THREAD

**Issue by iolyd** [CUPUM/cupum.github.io#21]
### Task description

Le site [`https://www.unesco-paysage.umontreal.ca`](https://www.unesco-paysage.umontreal.ca/) retourne présentement une erreur de sécurité. Le signalement résulte du supposé manque de certificat de sécurité, ou de son statut invalide pour l'adresse visitée.

Cette erreur pourrait être causée par différents éléments:

- La propagation de la redirection n'est pas encore complète: Peut prendre quelques jours avant d'être en fonction (généralement entre 24h - 48h)
- La redirection vise le sous domaine `www` de `unesco-studio.umontreal.ca`: Idéalement nous devrions aussi configurer le DNS pour accepter `https://www.unesco-studio.umontreal.ca` et non seulement `https://unesco-studio.umontreal.ca`.
- ~~**Fort probable**: Les fureteurs des visiteurs de l'ancien site retiennent en mémoire les détails de l'ancien certificat (du site wordpress) et identifient que le nouveau serveur ne correspond pas aux attentes, créant une erreur de sécurité.~~

### List of actions

- [x] Signaler le problème aux TI
- [x] Identifier causes potentielles
- [ ] [Configurer DNS pour sous-domaine `www` aussi](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant)
- [ ] [Compléter la vérification du domaine pour mitiger risques dans le futur](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages)

**Comment by iolyd** [comment]
@sjinko, pour ton info je vais suivre le problème ici.

**Comment by iolyd** [comment]
Après relecture des procédures à suivre, ça ne semble pas être une étape sautée lors de l'activation de `HTTPS`, tout devrait être en ordre de ce côté.
