### ISSUE TITLE
Task: Code navigator

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#25]
# Task description
Activate hamburger

# List of action:
- [x] Action: Check with ChatGPT for solution
- [x] Action: Implement HTML
- [x] Action: Implement CSS
- [x] Action: Implement JS

**Comment by sjinko** [comment]
- [ ] Action: Ask phone and social media on 600px navigator page
- [ ] Action: Remove white strip on 600px navigator bar
- [ ] Action: Change color of navigator logo on 600px
