### ISSUE TITLE
Task: Reoganise team section

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#27]
# Task description
We rework the Teams section to make is easier to navigate on the 600px format. The team should appear organized as follow:

- Chairholder - 0
- Research professionals - 2
- Associate researchers - 4
- Affiliate researchers - 5
- Postdoc researchers - 6
- Doctoral researchers - 7
- Graduate researchers - 8
- Undergraduate researchers - 10
- Research interns - 12

The team members should appear as a list

# List of actions:
- [ ] Action: Hide photo in 600px format 
- [ ] Action: Add ranking data to team members post pages
- [ ] Action: Change ranking parameters in Team archive
