### ISSUE TITLE
Epic: Make improvements to website layout

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#29]
# Epic description
Make improvement to the graphic layout of the GitHub chair's website based on comments by MB.

For comments from MB, see screenshots in notes

# List of task:
- [ ] Task: Make adjustements to news section
- [x] Task: Make adjustements to footer
- [ ] Task: Make adjustements to project page
- [ ] Task: Make adjustements to How can we help you section
- [ ] Task: Make adjustments to team section
- [ ] Task: Make adjustments to team member page
- [ ] Task: Make adjustments to hero
- [ ] Task: Make adjustments to Be part section
