### ISSUE TITLE
Task: Demander au CENR d'exporter le contenu du site Wordpress en JSON

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#4]
# Task description

# Actions

- [x] Écrire au CEN-R pour coordonner export
- [x] Déterminer format de l'export
- [x] Récupérer le(s) fichier(s)

**Comment by iolyd** [comment]
Nous aurons plus de nouvelles en début de semaine prochaine. Pour le moment j'anticipe que l'export sera un fichier SQL ou CSV, une fois le fichier sous la main je pourrai mieux évaluer si c'est profitable de générer les news / posts avec un script.

Réponses de B. Moore:

> Salut Emmanuel,
> 
> Je laisse la balle à Soizic pour le début de la semaine prochaine, elle connait mieux se volet que moi 🙂
> 
> Bonne journée et à bientôt!
> 
> Brian
> De : Emmanuel Beaudry Marchand <[emmanuel.beaudry.marchand@umontreal.ca](mailto:emmanuel.beaudry.marchand@umontreal.ca)>
> Envoyé : jeudi 7 mars 2024 12:55
> À : Brian Moore <[brian.moore@umontreal.ca](mailto:brian.moore@umontreal.ca)>
> Cc : Soizic Ernoult <[soizic.ernoult@umontreal.ca](mailto:soizic.ernoult@umontreal.ca)>; CEN - CEN-R <[info@cen.umontreal.ca](mailto:info@cen.umontreal.ca)>
> Objet : Re: Chaire UNESCO en paysage urbain - Exportation de données
>  
> Bonjour Brian,
>  
> Merci pour la réponse rapide, c’est apprécié!
>  
> Si possible, au moment venu la semaine prochaine, j’aimerais bien discuter brièvement du format de l’export (i.e. csv, json, ou sql) pour planifier quelques tâches de mon bord.
>  
> Merci encore et bonne journée,
>  
> Emmanuel Beaudry Marchand
> Agent de recherche
> Chaire UNESCO en paysage et environnement
> Université de Montréal
>  
> From: Brian Moore <[brian.moore@umontreal.ca](mailto:brian.moore@umontreal.ca)>
> Date: Thursday, March 7, 2024 at 10:56 AM
> To: Emmanuel Beaudry Marchand <[emmanuel.beaudry.marchand@umontreal.ca](mailto:emmanuel.beaudry.marchand@umontreal.ca)>
> Cc: Soizic Ernoult <[soizic.ernoult@umontreal.ca](mailto:soizic.ernoult@umontreal.ca)>, CEN - CEN-R <[info@cen.umontreal.ca](mailto:info@cen.umontreal.ca)>
> Subject: RE: Chaire UNESCO en paysage urbain - Exportation de données
> 
> Bonjour Emmanuel,
>  
> J'espère que tu vas bien. 
>  
> Je me permets de te répondre en suivi avec le courriel ci-dessous puisque Soizic et Christian sont absents cette semaine. 
>  
> Nous vous ferons parvenir l'export en début de semaine prochaine sans faute.
>  
> Merci et bon jeudi!
>  
> Brian

**Comment by iolyd** [comment]
Le CEN-R nous a partagé un export complet du site web, incluant la base de données SQL. Je ferme en faveur de #16
